apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: group-sync
  namespace: group-sync-operator
  labels:
    app: github-group-sync
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: group-sync-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
