apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: aapaas-managed-rbac
  namespace: rbac
  labels:
    app: aapaas-managed-rbac
  annotations:
    apps.open-cluster-management.io/github-path: rbac
    apps.open-cluster-management.io/reconcile-option: replace
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: acm-applications/aap-adoption-test
  placement:
    placementRef:
      name: aapaas-managed-rbac-deploy
      kind: PlacementRule