apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: github-group-sync-app
  namespace: group-sync-operator
  labels:
    app: github-group-sync
  annotations:
    apps.open-cluster-management.io/github-path: group-sync
    apps.open-cluster-management.io/reconcile-option: merge
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: acm-applications/aap-adoption-test
  placement:
    placementRef:
      name: github-group-sync-deploy
      kind: PlacementRule